/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type Project = {
  name?: string;
  description?: string;
};

export type Task = {
  project_id?: number;
  name?: string;
  description?: string;
};

export type LoginRequest = {
  email?: string;
  password?: string;
};

export type RegisterRequest = {
  email?: string;
  password?: string;
};

export type AuthResponse = {
  token?: string;
};

export type ErrorResponse = {
  message?: string;
};
